### ISSUE TITLE
Figure out how to have login manager load two different user types

### ISSUE THREAD

**Issue by avivalipkowitz** [avivalipkowitz/Doula_Project#7]
right now, the login manager part of the controller returns an id, and that's the user for the session. but it's only set up to query the Doula database, because I don't know how to have it set up for both. Which means that only doulas can sign in. Obviously we want parents to be able to sign in as well.

**Comment by avivalipkowitz** [comment]
i seem to have mostly sorted this out. it's totally doula#1 and parent#1 are getting stored in the session as the same person, which would be bad. i suppose i should test that by signing up more and more of only one user type, and making sure that they can get stored in the session (if the other user type is the only one being accessed, then it should return an error if i try to store a user id that doesn't exist in that table)

**Comment by meaganrgamache** [comment]
Is this fixed?

**Comment by avivalipkowitz** [comment]
This is fixed!
